// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PByhBGB5jWpmiYCOMI3mVMHPAcGGbyQ',
    appId: '1:464488566350:web:267101aa9d83ae1ac0bd1f',
    messagingSenderId: '464488566350',
    projectId: 'eurobingo-89864',
    authDomain: 'eurobingo-89864.firebaseapp.com',
    storageBucket: 'eurobingo-89864.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-PByhBGB5jWpmiYCOMI3mVMHPAcGGbyQ',
    appId: '1:464488566350:android:6e58a387b38396bbc0bd1f',
    messagingSenderId: '464488566350',
    projectId: 'eurobingo-89864',
    storageBucket: 'eurobingo-89864.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-PByhBGB5jWpmiYCOMI3mVMHPAcGGbyQ',
    appId: '1:464488566350:ios:38fa53d9fcbcfe6ac0bd1f',
    messagingSenderId: '464488566350',
    projectId: 'eurobingo-89864',
    storageBucket: 'eurobingo-89864.firebaseapp.com',
    iosBundleId: 'com.example.eurobingo-89864',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDapb-llg7r0iq1z8NJtkzEJc5H-zvN8',
    appId: '1:464488566350:ios:5e0d5a1bc0457e40321949',
    messagingSenderId: '464488566350',
    projectId: 'eurobingo-89864',
    storageBucket: 'eurobingo-89864.firebaseapp.com',
    iosBundleId: 'com.example.eurobingo-89864.RunnerTests',
  );
}
