// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOitm5svT3OtvD6A3hmf3g-jAC_IkqWls',
    appId: '1:163720975212:web:94157f7f20f8217d321949',
    messagingSenderId: '163720975212',
    projectId: 'eurobingo',
    authDomain: 'eurobingo.firebaseapp.com',
    storageBucket: 'eurobingo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wsoDTUFLbUgLTAJL8WyGQAO5uk48hwA',
    appId: '1:163720975212:android:a97842edfb35134f321949',
    messagingSenderId: '163720975212',
    projectId: 'eurobingo',
    storageBucket: 'eurobingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDapb-llg7r0iq1z8NJtkzEJc5H-zvN8',
    appId: '1:163720975212:ios:2d26fd7693572d03321949',
    messagingSenderId: '163720975212',
    projectId: 'eurobingo',
    storageBucket: 'eurobingo.appspot.com',
    iosBundleId: 'com.example.eurobingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDapb-llg7r0iq1z8NJtkzEJc5H-zvN8',
    appId: '1:163720975212:ios:5e0d5a1bc0457e40321949',
    messagingSenderId: '163720975212',
    projectId: 'eurobingo',
    storageBucket: 'eurobingo.appspot.com',
    iosBundleId: 'com.example.eurobingo.RunnerTests',
  );
}
